language: node_js
node_js:
  - "10"
  - "8"

services:
  - docker

env:
  global:
    - DEBUG=dtls,dtls:*
    - PRIORITY=NORMAL:+AEAD:+ECDHE-ECDSA:+ECDHE-RSA:+RSA:+PSK:+ECDHE-PSK:+VERS-DTLS1.2
  matrix:
    - CIPHER=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 KEYFILE=key-rsa.pem CERTFILE=cert-rsa.pem
    - CIPHER=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 KEYFILE=key-rsa.pem CERTFILE=cert-rsa.pem
    - CIPHER=TLS_RSA_WITH_AES_128_GCM_SHA256 KEYFILE=key-rsa.pem CERTFILE=cert-rsa.pem
    - CIPHER=TLS_RSA_WITH_AES_256_GCM_SHA384 KEYFILE=key-rsa.pem CERTFILE=cert-rsa.pem
    - CIPHER=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 KEYFILE=key-ecdsa.pem CERTFILE=cert-ecdsa.pem
    - CIPHER=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 KEYFILE=key-ecdsa.pem CERTFILE=cert-ecdsa.pem
    - CIPHER=TLS_PSK_WITH_AES_128_GCM_SHA256 KEYFILE=key-ecdsa.pem CERTFILE=cert-ecdsa.pem
    - CIPHER=TLS_PSK_WITH_AES_256_GCM_SHA384 KEYFILE=key-ecdsa.pem CERTFILE=cert-ecdsa.pem

matrix:
  include:
    - node_js: "11"
      env: CIPHER=TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 KEYFILE=key-rsa.pem CERTFILE=cert-rsa.pem
    - node_js: "11"
      env: CIPHER=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 KEYFILE=key-ecdsa.pem CERTFILE=cert-ecdsa.pem
    - node_js: "11"
      env: CIPHER=TLS_PSK_WITH_CHACHA20_POLY1305_SHA256 KEYFILE=key-ecdsa.pem CERTFILE=cert-ecdsa.pem
    - node_js: "11"
      env: CIPHER=TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 KEYFILE=key-ecdsa.pem CERTFILE=cert-ecdsa.pem

before_script:
  - docker run -d --name dtlsd -p 4444:4444/udp -e "GNUTLS_DEBUG_LEVEL=2" -e "KEYFILE=$KEYFILE" -e "CERTFILE=$CERTFILE" -e "PRIORITY=$PRIORITY" nodertc/dtls-server:1

script:
  - npm test
  - npm run integrated-test

after_script:
  - docker logs dtlsd
  - docker stop dtlsd
